# expectations of what the user may say in the beginning of his/her sentence
desires = ['i want to', 'i need to', 'i wish to', 'i demand to', 'i long to']


#most used of the word synonyms
createSynonyms = ['create', 'make', 'build', 'generate', 'conceive', 'design', 'establish', 'form', 'initiate', 'set up', 'invent']             



sentences = ['folder with all permissions', 
             'directory with all permissions', 
             'folder along all permissions', 
             'directory along all permissions', 
             'folder alongside with all permissions', 
             'directory alongside with all permissions',
             'folder alongside all permissions', 
             'directory alongside all permissions',
             'folders with all permissions', 'directories with all permissions', 
             'folders along all permissions', 'directories along all permissions', 
             'folders alongside with all permissions', 'directories alongside with all permissions', 
             'folders alongside all permissions', 'directories alongside all permissions', 
             'new folder with all permissions'
             'new directory with all permissions', 
             'new folder along all permissions', 
             'new directory along all permissions', 
             'new folder alongside with all permissions', 
             'new directory alongside with all permissions',
             'new folder alongside all permissions', 
             'new directory alongside all permissions',
             'folder for owner', 'new folder for owner',
             'directory for owner', 'new directory for owner',
             'folders for owner', 'new folders for owner', 'new folders for the owner',
             'directories for owner', 'new directories for owner',
             'brand new folder with all permissions', 
             'brand new directory with all permissions', 
             'brand new folder along all permissions', 
             'brand new directory along all permissions', 
             'brand new folder alongside with all permissions', 
             'brand new directory alongside with all permissions',
             'brand new folder alongside all permissions', 
             'brand new directory alongside all permissions',
             'folder for owner', 'brand new folder for owner',
             'directory for owner', 'brand new directory for owner',
             'folders for owner', 'brand new folders for owner',
             'directories for owner', 'brand new directories for owner',
             'folder with all privileges', 
             'directory with all privileges', 
             'folder along all privileges', 
             'directory along all privileges', 
             'folder alongside with all privileges', 
             'directory alongside with all privileges',
             'folder alongside all privileges', 
             'directory alongside all privileges',
             'folders with all privileges', 'directories with all privileges', 
             'folders along all privileges', 'directories along all privileges', 
             'folders alongside with all privileges', 'directories alongside with all privileges', 
             'folders alongside all privileges', 'directories alongside all privileges', 
             'new folder with all privileges'
             'new directory with all privileges', 
             'new folder along all privileges', 
             'new directory along all privileges', 
             'new folder alongside with all privileges', 
             'new directory alongside with all privileges',
             'new folder alongside all privileges', 
             'new directory alongside all privileges',
             'brand new folder with all privileges', 
             'brand new directory with all privileges', 
             'brand new folder along all privileges', 
             'brand new directory along all privileges', 
             'brand new folder alongside with all privileges', 
             'brand new directory alongside with all privileges',
             'brand new folder alongside all privileges', 
             'brand new directory alongside all privileges',
             'folder with complete permissions', 
             'directory with complete permissions', 
             'folder along complete permissions', 
             'directory along complete permissions', 
             'folder alongside with complete permissions', 
             'directory alongside with complete permissions',
             'folder alongside complete permissions', 
             'directory alongside complete permissions',
             'folders with complete permissions', 'directories with complete permissions', 
             'folders along complete permissions', 'directories along complete permissions', 
             'folders alongside with complete permissions', 'directories alongside with complete permissions', 
             'folders alongside complete permissions', 'directories alongside complete permissions', 
             'new folder with complete permissions'
             'new directory with complete permissions', 
             'new folder along complete permissions', 
             'new directory along complete permissions', 
             'new folder alongside with complete permissions', 
             'new directory alongside with complete permissions',
             'new folder alongside complete permissions', 
             'new directory alongside complete permissions',
             'brand new folder with complete permissions', 
             'brand new directory with complete permissions', 
             'brand new folder along complete permissions', 
             'brand new directory along complete permissions', 
             'brand new folder alongside with complete permissions', 
             'brand new directory alongside with complete permissions',
             'brand new folder alongside complete permissions', 
             'brand new directory alongside complete permissions',
             'folder with complete privileges', 
             'directory with complete privileges', 
             'folder along complete privileges', 
             'directory along complete privileges', 
             'folder alongside with complete privileges', 
             'directory alongside with complete privileges',
             'folder alongside complete privileges', 
             'directory alongside complete privileges',
             'folders with complete privileges', 'directories with complete privileges', 
             'folders along complete privileges', 'directories along complete privileges', 
             'folders alongside with complete privileges', 'directories alongside with complete privileges', 
             'folders alongside complete privileges', 'directories alongside complete privileges', 
             'new folder with complete privileges'
             'new directory with complete privileges', 
             'new folder along complete privileges', 
             'new directory along complete privileges', 
             'new folder alongside with complete privileges', 
             'new directory alongside with complete privileges',
             'new folder alongside complete privileges', 
             'new directory alongside complete privileges',
             'brand new folder with complete privileges', 
             'brand new directory with complete privileges', 
             'brand new folder along complete privileges', 
             'brand new directory along complete privileges', 
             'brand new folder alongside with complete privileges', 
             'brand new directory alongside with complete privileges',
             'brand new folder alongside complete privileges', 
             'brand new directory alongside complete privileges',
             'folder with full permissions', 
             'directory with full permissions', 
             'folder along full permissions', 
             'directory along full permissions', 
             'folder alongside with full permissions', 
             'directory alongside with full permissions',
             'folder alongside full permissions', 
             'directory alongside full permissions',
             'folders with full permissions', 'directories with full permissions', 
             'folders along full permissions', 'directories along full permissions', 
             'folders alongside with full permissions', 'directories alongside with full permissions', 
             'folders alongside full permissions', 'directories alongside full permissions', 
             'new folder with full permissions'
             'new directory with full permissions', 
             'new folder along full permissions', 
             'new directory along full permissions', 
             'new folder alongside with full permissions', 
             'new directory alongside with full permissions',
             'new folder alongside full permissions', 
             'new directory alongside full permissions',
             'brand new folder with full permissions', 
             'brand new directory with full permissions', 
             'brand new folder along full permissions', 
             'brand new directory along full permissions', 
             'brand new folder alongside with full permissions', 
             'brand new directory alongside with full permissions',
             'brand new folder alongside full permissions', 
             'brand new directory alongside full permissions',
             'folder with full privileges', 
             'directory with full privileges', 
             'folder along full privileges', 
             'directory along full privileges', 
             'folder alongside with full privileges', 
             'directory alongside with full privileges',
             'folder alongside full privileges', 
             'directory alongside full privileges',
             'folders with full privileges', 'directories with full privileges', 
             'folders along full privileges', 'directories along full privileges', 
             'folders alongside with full privileges', 'directories alongside with full privileges', 
             'folders alongside full privileges', 'directories alongside full privileges', 
             'new folder with full privileges'
             'new directory with full privileges', 
             'new folder along full privileges', 
             'new directory along full privileges', 
             'new folder alongside with full privileges', 
             'new directory alongside with full privileges',
             'new folder alongside full privileges', 
             'new directory alongside full privileges',
             'brand new folder with full privileges', 
             'brand new directory with full privileges', 
             'brand new folder along full privileges', 
             'brand new directory along full privileges', 
             'brand new folder alongside with full privileges', 
             'brand new directory alongside with full privileges',
             'brand new folder alongside full privileges', 
             'brand new directory alongside full privileges',
             'folder belong to owner', 'new folder belong to owner',
             'directory belong to owner', 'new directory belong to owner',
             'folders belong to owner', 'new folders belong to owner', 'new folders belong to the owner',
             'directories belong to owner', 'new directories belong to owner',
             'folder belong to owner', 'brand new folder belong to owner',
             'directory belong to owner', 'brand new directory belong to owner',
             'folders belong to owner', 'brand new folders belong to owner',
             'directories belong to owner', 'brand new directories belong to owner',
             
             
             
            ]



# this for loop is for giving a direct command from the user
count = 0
for z in desires:
    for x in createSynonyms:
        for y in sentences:
            print(z + ' ' + x + ' ' + y + ', mkdir -m 777')
            count = count + 1
print(count)


# this loop is to combine each list together the form of (i want to + <the synonyms> + the rest of the sentence)
count = 0
for x in createSynonyms:
    for y in sentences:
        print(x + ' ' + y + ', mkdir -m 777')
        count = count + 1
print(count)

